---
- name: Deploy IBM Security Guardium Virtual Appliance
  hosts: localhost
  vars_files:
    - vars.yml
  tasks:
    - name: Create VM from vCenter Server and attach ISO image to CD-ROM
      community.vmware.vmware_guest:
        validate_certs: false
        hostname: "{{ vcenter_hostname }}"
        username: "{{ vcenter_username }}"
        password: "{{ vcenter_password }}"
        name: "{{ vm_name }}"
        datacenter: "{{ datacenter }}"
        folder: "{{ vm_folder }}"
        state: poweredon
        guest_id: "{{ guest_id }}"
        disk:
          - size_gb: "{{ disk_size_gb }}"
            type: thin
            datastore: "{{ datastore }}"
        hardware:
          memory_mb: "{{ memory_mb }}"
          num_cpus: "{{ num_cpus }}"
          scsi: paravirtual
        cdrom:
          type: iso
          iso_path: "{{ iso_path }}"
        networks:
          - name: "{{ network_name }}"
            device_type: vmxnet3
        wait_for_ip_address: true
      register: vm_create

